---
title: "**SAUDE**"
subtitle: "**S**istema de **A**valiação e **U**so de **D**ados sobre **E**quilíbrio"
---

<br>

<center>
<video src="videos/index.mp4" width="100%" controls></video>
</center>

<br>

```{r accordeon, echo = FALSE}
bsplus::bs_accordion(id = "testes") |>
  bsplus::bs_set_opts(panel_type = "primary", use_heading_link = TRUE, open = FALSE) |>
  bsplus::bs_append(
    title =  htmltools::HTML("<span style='font-size: 30px; display: block; text-align: center; padding: 10px 30px 10px 30px;'>
                             Levantar e ir
                             <br>
                             <i class=\"fa-solid fa-chair\"></i>
                             <i class=\"fa-solid fa-person-walking-arrow-loop-left\"></i>
                             </span>"),
    content = htmltools::HTML(
      "<div style='font-size: 20px;'>
          Este teste avalia a sua mobilidade, equilíbrio e agilidade, medindo o tempo necessário para você completar um percurso que envolve caminhar, trocar de direção e realizar mudanças posturais. Esse teste fornece informações sobre a sua capacidade funcional e risco de quedas.
          <br><br>
          <center><a style='border: 2px solid #000; padding: 10px 20px; text-decoration: none; border-radius: 5px; display: inline-block;' href='timed-up-and-go.html'>TESTE AGORA!</a></center>
      </div>"
    )
  ) |>
  bsplus::bs_append(
    title =  htmltools::HTML("<span style='font-size: 30px; display: block; text-align: center; padding: 10px 30px 10px 30px;'>
                             Sentar e levantar
                             <br>
                             <i class=\"fa-solid fa-chair\"></i>
                             <i class=\"fa-solid fa-person\"></i>
                             <i class=\"fa-solid fa-up-down\"></i>
                             </span>"),
    content = htmltools::HTML(
      "<div style='font-size: 20px;'>
          Neste teste, são contadas quantas vezes você consegue se levantar e sentar de uma cadeira em 30 segundos. Esse exame avalia a sua força muscular, equilíbrio e agilidade.
          <br><br>
          <center><a style='border: 2px solid #000; padding: 10px 20px; text-decoration: none; border-radius: 5px; display: inline-block;' href='sentar-e-levantar.html'>TESTE AGORA!</a></center>
      </div>"
    )
  ) |>
  bsplus::bs_append(
    title =  htmltools::HTML("<span style='font-size: 30px; display: block; text-align: center; padding: 10px 30px 10px 30px;'>
                             Apoio unipodal
                             <br>
                             <i class=\"fa-solid fa-person\"></i>
                             </span>"),
    content = htmltools::HTML(
      "<div style='font-size: 20px;'>
          Este teste avalia a sua capacidade de manter o equilíbrio enquanto está em pé sobre uma perna. Esse exame é fundamental para a avaliação do seu equilíbrio estático.
          <br><br>
          <center><a style='border: 2px solid #000; padding: 10px 20px; text-decoration: none; border-radius: 5px; display: inline-block;' href='apoio-unipodal.html'>TESTE AGORA!</a></center>
      </div>"
    )
  )
```

```{r, echo=FALSE, results='asis'}
htmltools::tags$script(htmltools::HTML("
  document.addEventListener('DOMContentLoaded', function() {
    // Close all panels (remove Bootstrap's 'show' class)
    document.querySelectorAll('.collapse.in').forEach(function(el) {
      el.classList.remove('in');
    });
  });
"))
```
